# Generated by Django 5.2.1 on 2025-06-10 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_creator_teammembership_team_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Начало задачи')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='Конец задачи')),
                ('status', models.CharField(choices=[('OPEN', 'открыто'), ('IN_PROGRESS', 'в работе'), ('COMPLETED', 'выполнено')], default='OPEN', max_length=15, verbose_name='Статус задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор задачи')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-start_time', '-end_time'],
            },
        ),
    ]
