# Generated by Django 5.2.1 on 2025-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'Пользователь'), ('MG', 'Менеджер'), ('AD', 'Админ')], default='US', max_length=2, verbose_name='роль'),
        ),
    ]
